export type EvidenceLabel = "Verified primary fact" | "Company statement" | "Media report" | "Allegation" | "Internal document" | "Legal context" | "Evidence gap";

export type ResearchRecord = {
  id: string;
  title: string;
  summary: string;
  label: EvidenceLabel;
  date: string;
  topics: string[];
  source: string;
  citation: string;
  status: string;
  gap?: string;
};

export const evidenceLabels: {label: EvidenceLabel; definition: string}[] = [
  { label: "Verified primary fact", definition: "Supported by an identified primary record whose relevant content has been checked. This label does not validate broader conclusions." },
  { label: "Company statement", definition: "A statement published by or attributed to MECCA Brands Pty Ltd. It records what the company said, not whether the statement was implemented in every workplace." },
  { label: "Media report", definition: "Information reported by an identified news publisher. It is attributed to that publisher and is not treated as a primary finding." },
  { label: "Allegation", definition: "A claim that has not been established as fact. Allegations remain clearly attributed, qualified and subject to response." },
  { label: "Internal document", definition: "A status label for material supplied as internal. The site does not provide access to the source. Provenance, currency, contributor authority and publication clearance may remain unresolved." },
  { label: "Legal context", definition: "General information about Australian workplace law. It is not legal advice and does not determine whether any law was breached." },
  { label: "Evidence gap", definition: "A question that the available material does not answer, or a source that has not yet been obtained or authenticated." },
];

export const corporateHistory: ResearchRecord[] = [
  { id: "CH-001", title: "Company identity and scope", summary: "The research concerns MECCA Brands Pty Ltd and public or supplied material connected with its workplace systems. References to MECCA identify the subject, not an affiliation with this project.", label: "Verified primary fact", date: "Current scope", topics: ["Entity", "Methodology"], source: "Comprehensive Research Report, scope section", citation: "CRR-SCOPE", status: "Scope checked", gap: "Corporate relationships and historical entity changes require record-level citations before publication." },
  { id: "CH-002", title: "Corporate history chronology", summary: "Part A provides a working chronology for further source checking. Entries are not published as verified events until the underlying primary source is preserved and reviewed.", label: "Evidence gap", date: "Research record", topics: ["Corporate history", "Verification"], source: "Part A, Corporate History", citation: "A-CHRONOLOGY", status: "Source-by-source review required", gap: "Add exact dates, archived URLs and primary records before promoting individual chronology entries." },
  { id: "CH-003", title: "Archived employer representations", summary: "Supplied Wayback Machine captures record historical public-facing workplace statements. They establish what appeared in a capture, not whether the statements were current, accurate or consistently implemented.", label: "Company statement", date: "Historical capture", topics: ["Culture", "Employer brand"], source: "Supplied archived website captures", citation: "ARCH-EMP-01–03", status: "Capture supplied; original URL and timestamp not independently verified" },
  { id: "CH-004", title: "MECCA Brands IP entity record", summary: "The supplied corporate-history dossier records MECCA Brands IP Pty Ltd as an active Australian private company with ABN and ACN 43 609 957 100, GST-registered from 1 January 2016. The record is suitable for verification against ABN Lookup before publication as a standalone entity profile.", label: "Verified primary fact", date: "Registered 2015; GST from 1 Jan 2016", topics: ["Entity", "Ownership", "Corporate structure"], source: "MECCA Brands Corporate History, Ownership, Leadership and Workforce dossier", citation: "CORP-ENTITY-01", status: "Government-register reference identified", gap: "Obtain current ASIC extracts for the wider entity group and officeholder history." },
  { id: "CH-005", title: "Private ownership structure", summary: "Reporting synthesised in the supplied dossier describes MECCA as founder-controlled and privately held through a trust shareholder. The dossier did not establish the trust's legal name, trustees or beneficiaries.", label: "Media report", date: "Reported 2025–2026", topics: ["Ownership", "Governance", "Trust"], source: "Corporate-history dossier citing Inside Retail and business reporting", citation: "CORP-OWN-01", status: "Reported structure; beneficial ownership unresolved", gap: "Preserve the underlying company extract and identify the legal shareholder and ultimate beneficial ownership before presenting a definitive structure chart." },
  { id: "CH-006", title: "Large proprietary company reporting obligations", summary: "ASIC's 2026 action identifies MECCA Brands Pty Ltd, MECCA Brands NZ Pty Ltd and RTCH Pty Ltd in relation to alleged late lodgement of FY2024 audited financial reports. Payment of the notices was not an admission of guilt or liability.", label: "Verified primary fact", date: "31 March 2026", topics: ["Governance", "Financial reporting", "ASIC"], source: "ASIC media release 26-057MR", citation: "ASIC-26-057MR", status: "Official regulator record checked", gap: "The specific function and ownership relationship of RTCH Pty Ltd requires a current company extract and consolidated accounts." },
  { id: "CH-007", title: "Myer concession exit completed", summary: "The recent-developments dossier reports that MECCA completed the closure of its Myer concessions in June 2026, ending a 17-year partnership earlier than the previously announced September timetable.", label: "Media report", date: "June 2026", topics: ["Retail footprint", "Organisational change", "Myer"], source: "MECCA Brands recent-developments dossier citing company and retail reporting", citation: "RECENT-MYER-01", status: "Reported completion; underlying announcement should be preserved" },
  { id: "CH-008", title: "Expansion pipeline", summary: "Recent reporting compiled in the supplied dossier identifies a planned Chadstone megastore, a second Sydney city store at Martin Place and MECCA's first duty-free airport location, expected at Sydney International Airport in 2027. These are forward-looking announcements, not completed openings.", label: "Media report", date: "June–July 2026", topics: ["Expansion", "Stores", "Strategy"], source: "MECCA Brands recent-developments dossier citing AFR and company announcements", citation: "RECENT-EXPANSION-01", status: "Forward-looking plans; completion not verified" },
];

export const publicClaims: ResearchRecord[] = [
  { id: "PC-001", title: "Workplace culture representation", summary: "An archived public page described MECCA's workplace culture in favourable terms. This database records the representation without adopting it as a finding about employee experience.", label: "Company statement", date: "2019 capture supplied", topics: ["Culture", "Employer brand"], source: "Archived employer claim capture 01", citation: "ARCH-EMP-01", status: "Historical statement logged", gap: "Original page URL, full capture date and surrounding page context remain to be independently preserved." },
  { id: "PC-002", title: "Development planning source under legal review", summary: "A document represented as a 2024 MECCA guidebook was supplied to the project. Its source, excerpts and source-derived analysis are withheld pending provenance, authentication and qualified legal review.", label: "Internal document", date: "Represented as 2024", topics: ["Development", "Restricted source"], source: "Contributor-supplied material", citation: "INT-DPG-2024", status: "Pre-publication legal hold" },
  { id: "PC-003", title: "Recruitment and internal opportunity wording", summary: "A retrieval note summarises wording said to have appeared on an internal recruitment page, but the source page was not included in the evidence bundle.", label: "Evidence gap", date: "Collected 4 Aug 2026", topics: ["Recruitment", "Opportunity"], source: "Recruitment Policy retrieval note", citation: "GAP-REC-01", status: "Not retrieved", gap: "Obtain a dated page capture or policy copy before publishing any substantive recruitment claim." },
  { id: "PC-004", title: "Employee-review sentiment synthesis", summary: "The supplied review synthesis identifies recurring positive themes such as product training, staff benefits and peer relationships, alongside recurring criticism concerning management consistency, advancement, rostering and workload. These are self-selected, anonymous or pseudonymous opinions and cannot establish prevalence or company-wide conditions.", label: "Evidence gap", date: "Platforms reviewed 2019–2026", topics: ["Employee sentiment", "Review platforms", "Research lead"], source: "Recurring Themes in MECCA Employee Discourse dossier", citation: "SENTIMENT-SYNTHESIS-01", status: "Logged as a research lead only", gap: "A reproducible corpus, documented coding method, deduplication, role and location data, company response and representative survey evidence would be required before drawing broader conclusions." },
  { id: "PC-005", title: "Gender pay gap explanation", summary: "The supplied recent-developments dossier records MECCA's explanation that its reported average total-remuneration gender pay gap reflects workforce composition rather than unequal pay for equal roles. The statement should be compared with the underlying WGEA employer dataset and reported by measure, year and workforce group.", label: "Company statement", date: "2026 company publication", topics: ["Gender pay gap", "WGEA", "Workforce composition"], source: "MECCA gender pay data page, synthesised in recent-developments dossier", citation: "WGEA-MECCA-2026", status: "Company explanation logged; dataset cross-check required", gap: "Preserve the underlying WGEA employer data and reconcile average, median, base-salary and total-remuneration measures before comparison." },
];

export const internalDocuments: ResearchRecord[] = [
  { id: "ID-001", title: "Development Planning Guidebook", summary: "Contributor-supplied material represented as a 2024 MECCA guidebook. No source-derived content is published while provenance, contributor authority, authenticity and publication rights remain unresolved.", label: "Internal document", date: "Represented as 2024", topics: ["Restricted source", "Development"], source: "Contributor-supplied material", citation: "INT-DPG-2024", status: "Pre-publication legal hold", gap: "Qualified Australian media-law review is required before any source file, excerpt or analysis is published." },
  { id: "ID-002", title: "MECCA's Living Values", summary: "Values material supplied to the project. First-person expectations should not be recast as manager-specific duties without an additional source.", label: "Internal document", date: "2024", topics: ["Values", "Culture"], source: "MECCA Living Values 2024", citation: "INT-LV-2024", status: "Content reviewed; authentication pending" },
  { id: "ID-003", title: "Development Planning Guidebook implementation tools", summary: "The IDP, career meeting agenda, quarterly check-in and monthly 1:1 template are grouped as related implementation tools, not counted as independent corroboration of practice.", label: "Internal document", date: "Various metadata dates", topics: ["Templates", "Development"], source: "Supplied Office files", citation: "INT-TOOLS-01–04", status: "Content reviewed; dates and version relationships under review" },
  { id: "ID-004", title: "Performance and Growth Rating Scale", summary: "The supplied document identifies itself as a Support Centre rating scale. Its scope should not be extrapolated to retail, distribution, casual or international workforces.", label: "Internal document", date: "Date not established", topics: ["Support Centre", "Performance"], source: "Supplied PDF", citation: "INT-PGRS-01", status: "Scope identified; currency unconfirmed" },
  { id: "ID-005", title: "Workday completions reporting guide", summary: "An administrative guide demonstrates that a reporting workflow existed for authorised users. It does not establish that training occurred fairly or that records were used appropriately.", label: "Internal document", date: "Date not established", topics: ["Systems", "Training"], source: "Supplied PDF", citation: "INT-WD-01", status: "Restricted source; redaction required", gap: "Screenshots contain personal or employee-related information and must not be published unredacted." },
];

export const legalTopics: ResearchRecord[] = [
  { id: "LAW-001", title: "Workplace bullying", summary: "Part C provides a research framework for identifying potentially relevant law, evidence and procedural questions. Whether conduct meets a legal test depends on facts and the applicable forum.", label: "Legal context", date: "Research framework", topics: ["Bullying", "Fair Work"], source: "Part C, Australian Workplace Law Framework", citation: "C-BULLYING", status: "General context only" },
  { id: "LAW-002", title: "General protections and adverse action", summary: "The framework flags protections that may become relevant when a person exercises a workplace right. No legal conclusion is made about any account or organisation.", label: "Legal context", date: "Research framework", topics: ["General protections", "Retaliation"], source: "Part C, Australian Workplace Law Framework", citation: "C-GP", status: "General context only" },
  { id: "LAW-003", title: "Psychosocial hazards and work health and safety", summary: "The framework identifies psychosocial risk as a topic for evidence collection and legal review. Applicable duties vary by jurisdiction and current law.", label: "Legal context", date: "Research framework", topics: ["WHS", "Psychological safety"], source: "Part C, Australian Workplace Law Framework", citation: "C-WHS", status: "Current-law verification required before publication" },
  { id: "LAW-004", title: "Complaints, records and procedural fairness", summary: "Complaint handling records may help establish what was reported, when it was received and how it was addressed. A record does not by itself establish the truth of every underlying claim.", label: "Legal context", date: "Research framework", topics: ["Complaints", "Records"], source: "Part C, Australian Workplace Law Framework", citation: "C-COMPLAINTS", status: "General context only" },
  { id: "LAW-005", title: "Confidential sources and shield laws", summary: "The supplied legal framework describes Australian journalist-source privilege as rebuttable rather than absolute. Whether an independent documentary project qualifies, and whether an exception applies, depends on the relevant Evidence Act, the proceeding and the project's structure.", label: "Legal context", date: "Legal framework reviewed Aug 2026", topics: ["Sources", "Shield laws", "Confidentiality"], source: "Australian Legal Framework for Independent Workplace Investigations dossier", citation: "LEGAL-SHIELD-01", status: "Independent legal advice required before promising confidentiality", gap: "Obtain jurisdiction-specific advice on the project's status and the limits of privilege before publication or compulsory process." },
  { id: "LAW-006", title: "Recording and interview consent", summary: "Conversation-recording rules differ across Australian states and territories. Recording consent and permission to publish are separate questions, and cross-border interviews require location-specific review.", label: "Legal context", date: "Legal framework reviewed Aug 2026", topics: ["Recording", "Consent", "Documentary production"], source: "Australian Legal Framework for Independent Workplace Investigations dossier", citation: "LEGAL-RECORDING-01", status: "Operational legal review required", gap: "Adopt a jurisdiction-checked consent and release process before recording or publishing interviews." },
  { id: "LAW-007", title: "Whistleblower and workplace-right pathways", summary: "The supplied legal framework distinguishes Corporations Act qualifying disclosures from Fair Work Act workplace complaints. A disclosure made only to a journalist or documentary producer does not automatically receive the same statutory protection as one made through an authorised channel.", label: "Legal context", date: "Legal framework reviewed Aug 2026", topics: ["Whistleblowers", "General protections", "Source safety"], source: "Australian Legal Framework for Independent Workplace Investigations dossier", citation: "LEGAL-WB-01", status: "General information only; not advice to contributors", gap: "Contributors should obtain independent legal advice about their circumstances and any authorised reporting pathway." },
];

export const sourceRegister = [
  ["CRR", "Comprehensive Research Report", "Master synthesis", "Working research source"],
  ["A", "Part A: Corporate History", "Corporate chronology", "Underlying sources require record-level checking"],
  ["B", "Part B: Public Culture Claims", "Public statements register", "Claims must remain attributed"],
  ["C", "Part C: Australian Workplace Law Framework", "General legal context", "Not legal advice"],
  ["D", "Part D: Factual-Risk Audit", "Accuracy and publication-risk review", "Editorial control source"],
  ["E", "Part E: Stakeholder Review", "Stakeholder and response planning", "Working analysis"],
  ["F", "Part F: Turnover, Tenure & Financial Deep Dive", "Workforce and financial research synthesis", "Primary-source checks ongoing"],
  ["INT-LV", "MECCA's Living Values", "Supplied internal material", "Authentication and clearance pending"],
  ["INT-DPG", "Development Planning Guidebook", "Supplied internal material", "Restricted pending legal review"],
  ["CORP", "Corporate History, Ownership, Leadership and Workforce", "Evidence-led corporate dossier", "Primary and media references require record-level preservation"],
  ["EMP", "MECCA Brands Investigation series", "Employment, litigation and public-record synthesis", "Outcomes and allegations remain separately classified"],
  ["PEER", "Retail and beauty-sector peer benchmark", "Comparative workplace research", "Review samples are not directly comparable or representative"],
  ["METHOD", "Major-outlet investigation methods review", "Editorial methodology benchmark", "Comparator cases do not establish facts about MECCA"],
  ["LEGAL", "Australian Legal Framework for Independent Workplace Investigations", "General legal research", "Not legal advice; current jurisdiction-specific review required"],
  ["STAKE", "MECCA Brands stakeholder map", "Stakeholder and response planning", "Working analysis, not a finding"],
  ["RECENT", "MECCA Brands recent developments", "Time-bounded news synthesis", "Forward-looking announcements and unresolved figures remain attributed"],
  ["SENTIMENT", "Recurring Themes in MECCA Employee Discourse", "Review-platform and social-discourse synthesis", "Self-selected opinion; not prevalence evidence"],
];
