import Link from "next/link";
import { PageHero, SitePage } from "../../site-shell";

const sources = [
  {id:"REG-ASIC-001",title:"Infringement Notice M01700495",publisher:"Australian Securities and Investments Commission",date:"Paid 26 March 2026",label:"Verified primary fact",className:"verified-primary-fact",summary:"ASIC's public register links the notice for Mecca Brands Pty Ltd under section 1317DAM of the Corporations Act 2001. ASIC's media release states that the entity paid $198,000 after allegedly failing to lodge its FY24 audited financial report within the statutory timeframe.",limits:"The notice concerns an alleged contravention. ASIC states that payment is not an admission of guilt or liability and the company is not regarded as convicted of the alleged offence.",primary:"https://download.asic.gov.au/media/ysvdp00l/infringement-notice-mecca-brands-pty-ltd-m01700495.pdf",primaryLabel:"Open the official ASIC notice",external:"https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2026-releases/26-057mr-mecca-companies-pay-594-000-in-infringement-notices-for-failing-to-lodge-financial-reports-on-time/",externalLabel:"ASIC media release"},
  {id:"MEDIA-PED-001",title:"Mecca Is Investigating Claims Of Widespread Internal Bullying Made By Ex-Employees",publisher:"Pedestrian.TV",date:"19 November 2019",label:"Media report",className:"media-report",summary:"Pedestrian reported anonymous allegations from current and former workers, information attributed to the Young Workers Centre, and MECCA's response that it had hired an independent consultant to review workplace culture.",limits:"The article documents reporting, attributed accounts and a company response. It does not establish that each allegation occurred or that a systemic finding was made.",external:"https://www.pedestrian.tv/news/mecca-investigating-bullying-claims/",externalLabel:"Read original article"},
  {id:"MEDIA-SMH-001",title:"'It's all fake': Beauty giant Mecca facing bullying claims",publisher:"The Sydney Morning Herald",date:"17 November 2019",label:"Media report",className:"media-report",summary:"The linked report concerns workplace bullying claims and the public controversy reported in November 2019.",limits:"The page could not be directly retrieved during this review. It is logged as a supplied source link pending full article preservation and citation checking.",external:"https://www.smh.com.au/business/companies/its-all-fake-beauty-giant-mecca-facing-bullying-claims-20191117-p539q4.html",externalLabel:"Open supplied SMH link"},
  {id:"MEDIA-SMH-002",title:"How selfie culture helped Jo Horgan build a multimillion-dollar business",publisher:"The Sydney Morning Herald",date:"10 October 2017",label:"Media report",className:"media-report",summary:"A business profile supplied as historical context for MECCA's growth, leadership and public employer messaging.",limits:"Company descriptions or figures reported in a profile remain attributed statements unless supported by an identified primary record.",external:"https://www.smh.com.au/lifestyle/how-selfie-culture-helped-jo-horgan-build-a-multimilliondollar-business-20171010-gyxo0m.html",externalLabel:"Open supplied SMH link"},
  {id:"MEDIA-APA-001",title:"Beauty retailer Mecca discovers it owes staff $560,000",publisher:"Australian Payroll Association",date:"26 March 2023",label:"Media report",className:"media-report",summary:"The article reports that approximately 1,600 current and former employees were contacted after a historical payroll review identified roughly $560,000 in back-payments for work between 2016 and 2022.",limits:"This is a secondary report. It should not be described as a regulator determination or a finding of broader wage misconduct without the underlying review or an official regulator source.",external:"https://austpayroll.com.au/news-and-resources/beauty-retailer-mecca-discovers-it-owes-staff-560000",externalLabel:"Read corrected article link"},
];

export default function SourceEvidence(){return <SitePage><PageHero label="Research Centre / Public-source library" title="Open the public records behind the research"><p>This page links to official public records and attributed reporting. It explains what each source can establish and where its limits are, without treating public availability as permission to republish a publisher&apos;s photos or documents.</p></PageHero>
  <section className="rc-evidence-intro"><div><span>Collection status</span><strong>Five public source records</strong></div><div><span>Primary documents</span><strong>Official ASIC source linked</strong></div><div><span>Editorial rule</span><strong>Allegations are not findings</strong></div></section>
  <section className="rc-evidence-list">{sources.map(source=><article key={source.id} id={source.id.toLowerCase()}><header><span className={`rc-label ${source.className}`}>{source.label}</span><code>{source.id}</code></header><div className="rc-evidence-main"><div><p className="rb-kicker">{source.publisher} / {source.date}</p><h2>{source.title}</h2><p>{source.summary}</p></div><aside><strong>Evidence limit</strong><p>{source.limits}</p></aside></div><footer>{source.primary&&<a className="rb-button red" href={source.primary} target="_blank" rel="noreferrer">{source.primaryLabel}</a>}<a className="rb-button" href={source.external} target="_blank" rel="noreferrer">{source.externalLabel}</a></footer></article>)}</section>
  <section className="rb-section dark"><p className="rb-kicker">Linking to the official record</p><h2>The ASIC notice is opened from ASIC&apos;s own public register</h2><p className="rb-lede">Inside MECCA no longer hosts a duplicate PDF. The source button opens ASIC&apos;s official copy for Mecca Brands Pty Ltd, ACN 077 859 931, notice M01700495.</p><p className="rb-note">ASIC&apos;s related media release states that payment is not an admission of guilt or liability and that the companies are not regarded as convicted of the alleged offence.</p></section>
  <section className="rb-section"><p className="rb-kicker">How the collection was cleaned up</p><h2>A link is a lead until the material behind it is checked</h2><p className="rb-lede">The same Pedestrian URL was supplied more than once, so it is logged once. An outdated Australian Payroll Association link was updated to the publisher&apos;s current article path. If a paywall or retrieval restriction stopped a complete review, the record says so.</p><div className="rb-actions"><Link className="rb-button red" href="/methodology">How evidence is assessed</Link><Link className="rb-button" href="/research-centre/workforce-financial-data">Workforce and financial data</Link></div></section>
  </SitePage>}
