CREATE TABLE `submissions` (
	`id` text PRIMARY KEY NOT NULL,
	`date_received` integer NOT NULL,
	`contact_permission` integer DEFAULT false NOT NULL,
	`publication_permission` integer DEFAULT false NOT NULL,
	`interview_permission` integer DEFAULT false NOT NULL,
	`contributor_status` text,
	`broad_employment_period` text,
	`broad_region` text,
	`broad_role` text,
	`employment_status` text,
	`knowledge_type` text,
	`hearsay_elements` text,
	`event_period` text,
	`themes` text,
	`names_mentioned` text,
	`witnesses_mentioned` text,
	`internal_reporting_status` text,
	`internal_response` text,
	`supporting_records` text,
	`documents_received` integer DEFAULT false NOT NULL,
	`corroboration_status` text,
	`similar_account_references` text,
	`contradictions` text,
	`follow_up_questions` text,
	`identification_risk` text,
	`legal_review_status` text,
	`right_of_reply_status` text,
	`publication_status` text DEFAULT 'not_assessed' NOT NULL,
	`withdrawal_requested` integer DEFAULT false NOT NULL,
	`notes` text
);
