import Link from "next/link";
import { PageHero, SitePage } from "../../site-shell";
const kpis=[["Founded","13 Mar 1997","Mecca Brands Pty Ltd · ASIC record"],["FY25 revenue","$1.43B","Reported profit after tax $125.9M"],["ASIC notices · Mar 2026","$594,000","Three entities · late financial reports"],["2023 underpayment","$560,000","About 1,600 staff · company payroll audit"],["Culture claims catalogued","117","Working Part B claims register"],["Audit issues recorded","27","Snapshot dated 4 August 2026"]];
const timeline=[["13 Mar 1997","Mecca Brands Pty Ltd registered, as recorded in the identified ASIC infringement notice."],["8 Dec 2016","RTCH Pty Ltd registered as the current parent entity in the supplied research dossier."],["Oct to Nov 2019","Estée Laundry published anonymous workplace accounts; media reporting included named and anonymous testimony; MECCA announced an independent culture review."],["26 Mar 2023","A MECCA-commissioned payroll audit identified about $560,000 in underpayments across about 1,600 staff and was reported to the Fair Work Ombudsman."],["Jun 2023","Jo Horgan appointed a Member of the Order of Australia."],["2 to 26 Mar 2026","ASIC issued infringement notices relating to late financial reports and later confirmed total notices of $594,000 were paid."],["Apr 2026","Reported FY25 results stated $1.43 billion revenue and $125.9 million profit after tax."],["May 2026","MECCA's Innovate Reconciliation Action Plan for May 2026 to May 2028 was published."]];
const corrections=[["The Fair Work Ombudsman found MECCA underpaid staff in 2023","The issue was identified through a MECCA-commissioned payroll audit and self-reported. No FWO enforcement outcome has been identified in the current source record."],["There is a Whistleblower Protection Act 2013 (Cth)","No Act with that title exists. Relevant private-sector protections are principally contained in the Corporations Act 2001, while the PID Act applies to Commonwealth public officials."],["Victoria uses the model WHS Act","Victoria has its own Occupational Health and Safety Act 2004 and psychological-health regulations rather than the model WHS legislation."],["Reported headcount figures are directly comparable","Published figures of 8,000+, 7,000+ and 7,500+ use different dates or descriptions and cannot presently be reconciled."],["Women represent both 94% and 95% of the workforce","The available statements use both figures. The latest identified public statement reports 95%."],["M-POWER funding figures are consistent","Public figures described as $25 million over five years and more than $35 million since 2022 have not been reconciled in the current record."]];
const testimony=[["Narita Salima · named media account","Media report","Reported bullying and ridicule on the shop floor and dismissal after raising concerns in 2016."],["Anonymous former head-office worker","Media report","Described a cult-like environment and pressure to resign despite no identified performance issue."],["Anonymous former makeup artist","Media report","Reported that belittlement contributed to seeking psychological support."],["Multiple anonymous accounts","Allegation","Claims included unpaid overtime and concerns about HR effectiveness."],["Estée Laundry submissions","Social media","More than 50 anonymous or pseudonymous accounts were posted and remain unverified unless independently corroborated."]];
const reportParts=[["A","Corporate history","1997 to 2026 chronology, entities and source checking"],["B","Culture claims","117-entry working register with evidence classes"],["C","Legal framework","General legal context across 11 topics"],["D","Factual-risk audit","27 issues across 10 publication-risk categories"],["E","Stakeholder review","Six perspectives and 25 working recommendations"],["G","2019 public allegations","Estée Laundry and media-reporting deep dive"]];
const gaps=["Current ASIC director and shareholder extracts","Lodged financial reports","2019 to 2020 culture review findings","WGEA employer-level data","New Zealand company registration","Current complaints, conduct and safety policies","M-PACT spend against stated commitment","Casual and permanent workforce split"];
function Bar({label,value,max,tone}:{label:string;value:number;max:number;tone?:string}){return <div className="rd-bar-row"><span>{label}</span><div className="rd-bar-track"><i className={tone||""} style={{width:`${value/max*100}%`}}/></div><strong>{value.toLocaleString()}</strong></div>}
export default function ResearchDashboard(){return <SitePage><PageHero label="Research Centre · Dashboard" title="A dated snapshot of the investigation"><p>This page brings together corporate history, reported workforce figures, public allegations, corrections, audit findings and evidence gaps. It is a way into the source material, not a substitute for it.</p><p><strong>Compiled 4 August 2026.</strong> The figures and audit observations belong to that date. They may change as sources are checked and the website is updated.</p><div className="rb-actions"><Link className="rb-button red" href="/research-centre/source-evidence">See the underlying sources</Link><Link className="rb-button" href="/methodology">How to read the evidence</Link></div></PageHero>
<section className="rd-kpis" aria-label="Investigation headline figures">{kpis.map(([label,value,note])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
<section className="rd-section"><div className="rd-heading"><p className="rb-kicker">Corporate timeline</p><h2>Events with an identified date and source</h2><p>The entries draw on primary records, company statements and attributed media reporting. The evidence label stays attached to each underlying record.</p></div><div className="rd-timeline">{timeline.map(([date,text])=><article key={date}><time>{date}</time><p>{text}</p></article>)}</div></section>
<section className="rd-section dark"><div className="rd-heading"><p className="rb-kicker">Workforce figures and source mix</p><h2>What is in the current record</h2></div><div className="rd-chart-grid"><article><h3>Reported headcount at different dates</h3><p>The sources use different dates and descriptions, so these figures are not treated as one consistent time series.</p><Bar label="End 2023" value={8000} max={8000}/><Bar label="End 2024" value={7000} max={8000}/><Bar label="Mar 2026" value={7500} max={8000}/></article><article><h3>How the 2019 sources are classified</h3><p>The counts describe the working source set. They do not show how common any workplace experience was.</p><Bar label="Verified" value={5} max={5} tone="ok"/><Bar label="Reported" value={5} max={5}/><Bar label="Alleged" value={2} max={5} tone="warn"/><Bar label="Social media" value={2} max={5} tone="risk"/></article></div></section>
<section className="rd-section"><div className="rd-heading"><p className="rb-kicker">Claims worth correcting</p><h2>What people repeat, compared with what the source actually says</h2><p>These notes keep a broader claim from outrunning the record behind it.</p></div><div className="rd-corrections" role="table" aria-label="Corrections to commonly repeated claims">{corrections.map(([claim,correction])=><div role="row" key={claim}><strong role="cell">{claim}</strong><p role="cell">{correction}</p></div>)}</div></section>
<section className="rd-section dark"><div className="rd-chart-grid"><article><p className="rb-kicker">Website audit snapshot</p><h2>27 recorded issues</h2><p>The supplied audit recorded five high-risk, eleven medium-risk and eleven lower-risk issues. This is a dated editorial snapshot, not a claim about the current live site.</p><Bar label="High risk" value={5} max={11} tone="risk"/><Bar label="Medium risk" value={11} max={11} tone="warn"/><Bar label="Lower risk" value={11} max={11} tone="ok"/><p className="rd-caution">Audit observations must be rechecked against the live site before they are described as current. Several submission pathways have changed since the snapshot was prepared.</p></article><article><p className="rb-kicker">Named and anonymous testimony</p><h2>2019 public allegations</h2><div className="rd-testimony">{testimony.map(([source,label,claim])=><div key={source}><span className={`rd-label ${label.toLowerCase().replaceAll(" ","-")}`}>{label}</span><strong>{source}</strong><p>{claim}</p></div>)}</div></article></div></section>
<section className="rd-section"><div className="rd-heading"><p className="rb-kicker">How the research is organised</p><h2>Six parts of the same investigation</h2></div><div className="rd-parts">{reportParts.map(([letter,title,meta])=><article key={letter}><span>{letter}</span><h3>{title}</h3><p>{meta}</p></article>)}</div></section>
<section className="rd-section dark"><div className="rd-heading"><p className="rb-kicker">What we do not have yet</p><h2>Evidence gaps that still matter</h2><p>These items need more primary-source research before we can draw firm conclusions.</p></div><div className="rd-gaps">{gaps.map(gap=><span key={gap}>{gap}</span>)}</div></section>
<section className="rd-notice"><strong>Editorial notice</strong><p>Background research for investigative purposes only. It is not legal advice. Allegations are unproven unless established by a court, tribunal or regulator, and remain subject to corroboration and response.</p><Link href="/legal-publication-policy">Read the legal and publication policy</Link></section></SitePage>}
