import Link from "next/link";
import { PageHero, SitePage } from "../site-shell";
import { categories, documents } from "./data";
import { DocumentExplorer } from "./explorer";

export default function EmployerCommitmentsPage() {
  return <SitePage><div className="ec-archive">
    <PageHero label="Employer commitments" title="What MECCA said its workplace should be" dark><p>This archive brings together independent, paraphrased research reconstructions and historical public statements. It helps compare stated expectations with employee experience while keeping source types separate.</p><div className="ec-hero-stats"><span><strong>{documents.filter((document) => document.status === "Reviewed").length}</strong> reconstructed records</span><span><strong>69</strong> research locators</span><span><strong>1</strong> known gap</span></div></PageHero>

    <section className="ec-section ec-intro"><p className="rb-kicker">Before you browse</p><div className="ec-two"><h2>These pages are independent reconstructions, not official MECCA documents.</h2><div><p>No internal file, scan, screenshot, extract or download is provided in this archive. The public pages use original wording written by Inside MECCA to describe research themes and questions.</p><p>A reconstruction may help identify what should be tested. It does not authenticate a source, establish permission to disclose it, prove that a process existed in the stated form, or show what happened in practice.</p><p>We keep organisational-source material and contributor testimony as separate evidence categories.</p></div></div></section>

    <section className="ec-section ec-public-archive" id="archived-public-statements"><p className="rb-kicker">Public-source record</p><div className="ec-heading-row"><h2>The facts remain available without republishing workplace photographs</h2><div><p>The earlier supplied page captures have been replaced with text-only evidence cards and direct links to publicly accessible sources. Public availability does not necessarily make an image or publication copyright-free.</p></div></div><div className="ec-source-cards">
      <article><span className="rc-label company-statement">Published ranking</span><p className="ec-meta">Great Place to Work Australia / 2019</p><h3>MECCA Brands ranked fourth in the 1,000-plus employee category</h3><p>The published study lists MECCA Brands at number four with 2,873 people. It says two-thirds of the ranking score came from employee survey responses and one-third from an assessment of policies and procedures.</p><p className="ec-source-limit"><strong>Limit:</strong> A ranking records the study result. It does not establish that every employee had the same experience.</p><a className="ec-text-link" href="https://www.cultureincorporated.com.au/wp-content/uploads/2019/09/2019_BPTWstudy.pdf" target="_blank" rel="noreferrer">Open the publicly accessible 2019 study</a></article>
      <article><span className="rc-label company-statement">Published ranking</span><p className="ec-meta">Great Place to Work Australia / 2018</p><h3>MECCA Brands ranked fifth in the 1,000-plus employee category</h3><p>The published study lists MECCA Brands at number five with 2,587 people. Contemporary reporting described this as MECCA&apos;s fifth consecutive year on the list.</p><p className="ec-source-limit"><strong>Limit:</strong> The rank and participation history do not prove any wider claim about workplace conditions.</p><div className="ec-resource-actions"><a className="ec-text-link" href="https://s3.amazonaws.com/bestworkplacesdb/publications/AU_2018_BPTW_EN.pdf" target="_blank" rel="noreferrer">Open the 2018 study</a><a className="ec-text-link" href="https://insideretail.com.au/news/mecca-loccitane-named-best-places-to-work-201808" target="_blank" rel="noreferrer">Read the contemporary report</a></div></article>
      <article><span className="rc-label company-statement">Current company statement</span><p className="ec-meta">MECCA / accessed 12 August 2026</p><h3>MECCA publishes current workforce and learning figures</h3><p>MECCA&apos;s gender pay data page says it has more than 7,500 team members, 95 per cent are women, 82 per cent work in stores and about 3 per cent of turnover is committed to learning and engagement.</p><p className="ec-source-limit"><strong>Limit:</strong> These are attributed company figures. They are not independently audited or treated as findings by this project.</p><a className="ec-text-link" href="https://www.mecca.com/en-au/m-pact/people/gender-pay-data/" target="_blank" rel="noreferrer">Open MECCA&apos;s published page</a></article>
    </div><p className="ec-caption">Inside MECCA links to the original public sources instead of hosting copied photographs, logos or page captures. Linked publications remain the property of their respective publishers.</p></section>

    <section className="ec-section"><p className="rb-kicker">Browse by topic</p><h2>Which workplace commitment are you looking for?</h2><div className="ec-category-grid">{categories.map((category) => <Link href={`/employer-commitments/categories/${category.slug}`} className="ec-category" key={category.slug}><h3>{category.name}</h3><p>{category.description}</p><small>{category.documentSlugs.length} linked {category.documentSlugs.length === 1 ? "record" : "records"}</small></Link>)}</div></section>

    <section className="ec-section" id="document-explorer"><p className="rb-kicker">Independent reconstructions</p><div className="ec-heading-row"><h2>Search the research records</h2><p>Nine paraphrased reconstructions and one disclosed retrieval gap. No original source file is available here.</p></div><DocumentExplorer documents={documents} categoryNames={categories.map((category) => category.name)} /></section>

    <section className="ec-integrity"><p className="rb-kicker">What this archive cannot establish</p><h2>Important limits on the reconstructed records</h2><p>The pages are original editorial summaries, not copies or substitute versions of internal documents. They do not reproduce source layouts, screenshots, quotations, identifiers or downloads.</p><p>Original internal files remain outside public access while authenticity, confidentiality, privacy, copyright, contributor authority and publication issues are assessed.</p></section>
  </div></SitePage>;
}
