"use client";

import { FormEvent, useState } from "react";
import { PolicyFooter, PolicyHeader } from "../policy-layout";

const roles = [
  ["Research and verification collaborator", "Review public records, build chronologies and document sources. Strong attention to detail and confidentiality required.", "Seeking expressions of interest"],
  ["Interview support collaborator", "Help prepare interviews, organise consent notes and support contributor follow-up. Trauma-informed communication experience is valued.", "Seeking expressions of interest"],
  ["Editorial reviewer", "Review structure, clarity, evidence labels and fairness. Journalism, documentary or publishing experience preferred.", "Future vacancy"],
  ["Production collaborator", "Assist with research logs, transcripts, release forms and documentary production planning.", "Future vacancy"],
];

export default function JoinPage() {
  const [sent,setSent]=useState(false);
  function apply(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const body=["INSIDE MECCA COLLABORATOR APPLICATION","",`Name: ${data.get("name")}`,`Email: ${data.get("email")}`,`Role: ${data.get("role")}`,`Location/time zone: ${data.get("location")}`,`Availability: ${data.get("availability")}`,"","Relevant experience:",data.get("experience"),"","Why this project:",data.get("motivation"),"","Conflicts or relevant connections:",data.get("conflicts")].join("\n");window.location.href=`mailto:contact@insidemecca.net?subject=${encodeURIComponent("Inside MECCA collaborator application")}&body=${encodeURIComponent(body)}`;setSent(true)}
  return <main><PolicyHeader /><section className="policy-hero"><p className="kicker">Work with the project</p><h1>Could your experience help this investigation?</h1><p>Inside MECCA is looking for careful, reliable people who can help with research, interviews, editing and production. These are unpaid project roles. Access depends on the role, the work available, relevant experience and conflict checks.</p></section><section className="roles-section"><div className="section-intro"><p className="kicker">Ways to contribute</p><h2>Roles we are building around</h2></div><div className="role-grid">{roles.map(([title,copy,status])=><article key={title}><span>{status}</span><h2>{title}</h2><p>{copy}</p></article>)}</div><div className="expectations"><h2>What working together would require</h2><ul><li>Respect for confidentiality and informed consent</li><li>Reliable communication and realistic time commitments</li><li>Careful documentation and review</li><li>Disclosure of relevant conflicts</li><li>No unauthorised contact with sources, subjects or media</li></ul><p>This is unpaid collaboration, not employment. We will agree the scope, ownership, confidentiality, credit and any expenses before work begins.</p></div></section><section className="application-section"><div><p className="kicker light">Expression of interest</p><h2>Tell us where you could help</h2><p>Your answers will open in your email app so you can review them before sending. Do not include confidential employer information or sensitive documents.</p></div>{sent?<div className="application-success"><h2>Your draft is ready</h2><p>Review it in your email app before you send it.</p><button className="button pale" onClick={()=>setSent(false)}>Start another</button></div>:<form onSubmit={apply}><label>Name<input required name="name" /></label><label>Email<input required type="email" name="email" /></label><label>Role<select required name="role"><option value="">Select a role</option>{roles.map(([r])=><option key={r}>{r}</option>)}</select></label><label>Location and time zone<input required name="location" /></label><label>Typical availability<input required name="availability" placeholder="For example, 3 hours per week" /></label><label>Relevant experience<textarea required rows={4} name="experience" /></label><label>Why do you want to help?<textarea required rows={4} name="motivation" /></label><label>Conflicts or relevant connections<textarea rows={3} name="conflicts" placeholder="Include current or previous connections to MECCA or related parties, or write None" /></label><label className="check"><input required type="checkbox" /> I understand this is an expression of interest and agree to discuss confidentiality before accessing project material.</label><button className="button pale" type="submit">Open email application</button></form>}</section><PolicyFooter /></main>;
}
