import Link from "next/link";
import type { Metadata } from "next";
import { SitePage } from "./site-shell";
import { inquiryAreas } from "./research-data";
import { buildMetadata } from "./seo";

const faqs=[
  ["Do I need documents?","No. First-hand testimony matters, and many workplace experiences leave little or no documentary record. Records can help corroborate an account when they exist."],
  ["Will you publish what I submit?","Not unless you separately agree to publication. Sending information to Inside MECCA is not permission to publish it."],
  ["Can I stay anonymous?","Yes. You can choose between anonymous, pseudonymous and confidential-contact options. There is a trade-off: fully anonymous accounts can be harder to verify because we cannot contact the contributor with follow-up questions."],
  ["Does submitting make me a protected whistleblower?","Not automatically. Inside MECCA is not a whistleblower hotline, regulator or law firm, and statutory protection depends on specific legal requirements. Get independent advice if you are relying on it."],
  ["Will my account be treated as proven?","It is assessed in context, including what you directly know, the level of detail provided, consistency, source independence, available corroboration and evidence pointing in another direction."],
  ["How do you count multiple reports?","The primary unit is one eligible submission from one contributor. Duplicate or linked material is not counted as though it came from independent sources, and submission numbers do not tell us how common an experience was across MECCA's entire workforce."]
];

export const metadata: Metadata = buildMetadata({ title:"MECCA Workplace Culture & Employee Experiences", description:"Independent analysis of working at MECCA, employee experiences, management, workplace culture, company commitments and evidence-led reform.", path:"/" });

const plannedOutputs=[
  ["Research framework","Published","The questions, modules and boundaries governing the investigation."],
  ["Evidence repository","In development","A source-labelled archive of records, commitments, public materials and evidence gaps."],
  ["Employee case studies","In development","De-identified accounts published only with separate permission and appropriate context."],
  ["Written investigation","Planned","Findings organised by research question, including evidence strength, contradictions and company response."],
  ["Documentary","In development","Narrative interviews and evidence-led reporting kept distinct from the research questionnaire."],
  ["Recommendations report","Planned","Practical proposals for MECCA, employees, industry and policymakers based on supported findings."],
];

export default function Home(){return <SitePage>
<section className="rb-hero"><div className="rb-hero-copy"><p className="rb-kicker">For current and former MECCA employees</p><h1>Worked at MECCA? Tell us what happened.</h1><p className="rb-lede">If you worked at MECCA, we want to hear what you experienced or directly witnessed.</p><p>Inside MECCA is documenting workplace experiences and comparing them with company policies, public commitments, records and other available evidence. The aim is to understand what happened in practice, where experiences differ, and whether the same issues appear across different stores, roles or periods of time.</p><p>Your experience might be one piece of a much bigger picture.</p><div className="rb-actions"><Link className="rb-button red" href="/share-story" data-analytics-event="share_path_click" data-analytics-detail="homepage_hero">Share your MECCA experience</Link><Link className="rb-button" href="/evidence" data-analytics-event="content_path_click" data-analytics-detail="homepage_hero_evidence">See how evidence is assessed</Link></div></div><aside className="rb-cinematic rb-control-panel" aria-label="Your participation choices"><p className="rb-kicker">Your participation, your terms</p><p>You decide how you take part. You choose what you tell us, whether you identify yourself, and whether we can contact you afterwards.</p><p>Submitting your experience does not give us permission to publish it. Publication requires separate consent.</p></aside></section>
  <div className="rb-independence-bar">Inside MECCA is an independent MECCA workplace investigation and is not affiliated with, endorsed by or operated by MECCA Brands.</div>
  <section className="rb-section seo-entry"><div className="rb-split"><div><p className="rb-kicker">MECCA workplace culture</p><h2>What was it actually like to work at MECCA?</h2></div><div className="rb-lede"><p>Public reviews can tell us something about a workplace, but they have limits. They are anonymous, self-selecting and often impossible to independently verify. Inside MECCA looks beyond individual reviews. We are examining employee accounts alongside company commitments, management practices, available records and other evidence to understand where MECCA&apos;s stated workplace standards matched employees&apos; experiences, and where they may not have.</p><p>Positive experiences matter too. An investigation looking for patterns has to be capable of finding disagreement, variation and evidence that contradicts its assumptions.</p><p>Explore the source-labelled records about <Link href="/employer-commitments/categories/career-development">career progression and development at MECCA</Link>, <Link href="/employer-commitments/categories/performance-feedback">performance reviews and feedback</Link>, and the public-source guide to <Link href="/analysis/mecca-complaints-whistleblower-policy">MECCA complaints and whistleblower pathways</Link>.</p><div className="rb-actions"><Link className="rb-button red" href="/analysis/working-at-mecca-reviews" data-analytics-event="content_path_click" data-analytics-detail="homepage_workplace_analysis">Read the workplace culture analysis</Link><Link className="rb-button" href="/analysis" data-analytics-event="content_path_click" data-analytics-detail="homepage_analysis_index">Browse all analysis</Link></div></div></div></section>
  <section className="rb-section dark strategy-section" id="goal"><p className="rb-kicker">Purpose and change</p><h2>What are we trying to change?</h2><div className="rb-lede"><p>The goal is not simply to publish stories about MECCA. It is to build a credible body of evidence that can support meaningful, measurable workplace change: documenting what employees say happened, testing those accounts against other evidence, identifying patterns where the evidence supports them, and being equally clear when it does not.</p><p>If problems are established, we want the response to be something people can actually assess: safer ways to raise concerns, fairer people practices, meaningful employee voice and evidence that promised changes have happened. Attention can create pressure. It is not the same thing as accountability.</p><p>We will compare experiences across stores, teams, managers, roles and time periods, examine MECCA&apos;s documented commitments, look for contradictions and seek responses where appropriate. From there, the question is simple: what can the evidence actually support?</p><p>The project may produce case studies, written findings, an evidence repository, documentary reporting and recommendations for reform, but none of those outputs should outrun the evidence behind them. The longer-term test is whether supported findings lead to changes that employees and the public can independently assess.</p></div><div className="rb-actions"><Link className="rb-button red" href="/change-agenda" data-analytics-event="content_path_click" data-analytics-detail="homepage_change_agenda">See the path to impact</Link><Link className="rb-button" href="/accountability" data-analytics-event="content_path_click" data-analytics-detail="homepage_accountability">How success is judged</Link></div></section>
  <section className="rb-section"><p className="rb-kicker">Taking part</p><h2>You can help in more than one way</h2><div className="rb-grid">{[["If you worked at MECCA","Tell us what you experienced or directly witnessed.","/share-story","Share your MECCA experience"],["If you have relevant records","Read the source-safety guidance before providing them.","/share-story/evidence","Provide records"],["If you know someone who worked there","Send them the site privately and let them decide whether they want to take part.","mailto:?subject=Have%20you%20worked%20at%20MECCA%3F&body=I%20thought%20you%20might%20want%20to%20see%20this%20independent%20workplace%20investigation%3A%20https%3A%2F%2Finsidemecca.net%2F","Send the site"]].map(([t,d,h,c])=><article className="rb-card" key={t}><h3>{t}</h3><p>{d}</p>{h.startsWith("mailto:")?<a href={h} data-analytics-event="private_share_click" data-analytics-detail="email_share">{c}</a>:<Link href={h} data-analytics-event={h === "/share-story" ? "share_path_click" : "content_path_click"} data-analytics-detail={h === "/share-story" ? "homepage_participation" : "homepage_source_safety"}>{c}</Link>}</article>)}</div></section>
  <section className="rb-section dark"><p className="rb-kicker">Why take part</p><h2>Why your account matters</h2><div className="rb-lede"><p>One experience cannot tell us what an entire workplace is like. But multiple independent accounts can help establish whether something is a pattern rather than a one-off, across different stores, teams, managers, roles and periods of time.</p><p>What contributors tell us also helps determine where the investigation goes next: what questions need more evidence, and which issues warrant deeper examination.</p></div><p className="rb-note">Taking part does not guarantee that your account will be published, that a particular finding will be reached, or that MECCA will make changes.</p></section>
  <section className="rb-section"><p className="rb-kicker">Research scope</p><h2>What we are investigating</h2><p className="rb-lede">The investigation currently covers several parts of working life at MECCA.</p><div className="rb-grid">{inquiryAreas.slice(0,6).map(([t,d])=><article className="rb-card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><p className="rb-note">These areas guide evidence collection. They are not findings in themselves.</p><div className="rb-actions"><Link className="rb-button" href="/areas-of-inquiry" data-analytics-event="content_path_click" data-analytics-detail="homepage_research_topics">See all research topics</Link></div></section>
  <section className="rb-section dark"><p className="rb-kicker">Current work</p><h2>Development, management and speaking up</h2><p className="rb-lede">A supplied 2024 development-planning document is currently on a pre-publication legal hold. Neither the source nor analysis derived from it will be published unless questions around authenticity, provenance, contributor authority and publication clearance are resolved.</p><div className="rb-actions"><Link className="rb-button red" href="/investigation/development-planning" data-analytics-event="content_path_click" data-analytics-detail="homepage_development_planning">Read the review status</Link><Link className="rb-button" href="/updates" data-analytics-event="content_path_click" data-analytics-detail="homepage_updates">See project updates</Link></div></section>
  <section className="rb-section"><p className="rb-kicker">Evidence</p><h2>How we assess evidence</h2><div className="rb-lede"><p>We do not treat a submission as proof simply because it has been submitted. Accounts are assessed for things such as direct knowledge, specificity, consistency, source independence, available corroboration and conflicting evidence. Relevant records and company responses are considered where available.</p><p>Sometimes the evidence will support a finding. Sometimes it will support only part of a claim. Sometimes it will not be strong enough to reach a conclusion. Those distinctions matter.</p><p>Contributors are self-selecting. The experiences submitted to Inside MECCA should not be treated as a representative sample of everyone who has worked for the company.</p></div><Link className="rb-button red" href="/evidence" data-analytics-event="content_path_click" data-analytics-detail="homepage_evidence_standards">Read the evidence standards</Link></section>
  <section className="rb-section dark"><p className="rb-kicker">Published and planned work</p><h2>What will Inside MECCA publish?</h2><p className="rb-lede">Some parts of the project already exist. Others are still being developed. We show the status of this work rather than presenting planned material as though it already exists.</p><div className="output-grid">{plannedOutputs.map(([t,s,d])=><article key={t}><span className={`output-status ${s.toLowerCase().replace(" ","-")}`}>{s}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="rb-actions"><Link className="rb-button" href="/updates">Track current progress</Link></div></section>
  <section className="rb-section"><div className="rb-split"><div><p className="rb-kicker">About the project</p><h2>Who is behind Inside MECCA?</h2></div><div className="rb-lede"><p>Inside MECCA was established by a former MECCA employee. The project lead is using a public pseudonym during the research and production stage. Further employment and identifying details are being withheld for privacy and safety.</p><p>This reduces casual identification risk, but it cannot guarantee anonymity against valid legal processes or records held by service providers. The founder&apos;s former employment and the project&apos;s advocacy purpose are disclosed as relevant perspective.</p><p>Inside MECCA is an independent research, documentary and advocacy project. It is not MECCA&apos;s whistleblower hotline, an employee representative body, a regulator, a legal practice or an emergency service.</p><div className="rb-actions"><Link className="rb-button red" href="/accountability">Read the accountability disclosure</Link><Link className="rb-button" href="/methodology">Read the investigation method</Link></div></div></div></section>
  <section className="rb-section rb-faq dark" id="faq"><p className="rb-kicker">FAQ</p><h2>Questions people reasonably ask</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  <section className="rb-section" id="source-safety"><p className="rb-kicker">Source safety</p><h2>Before sending records</h2><p className="rb-lede">Think about how you are sending them, not just what you are sending. Where possible, use a personal device, personal email address and personal network rather than workplace systems. Documents and images can contain metadata you may not realise is there.</p><p>Only provide material you are legally entitled to possess. If something is particularly sensitive, contact Inside MECCA before sending it.</p><p className="rb-note">No online system can promise absolute anonymity.</p><div className="rb-actions"><Link className="rb-button" href="/share-story/evidence">Read the source-safety guide</Link></div></section>
  <section className="rb-section dark" id="contact"><p className="rb-kicker">Worked at MECCA?</p><h2>Start with what you know first-hand.</h2><p className="rb-lede">You do not need perfect dates. You do not need to remember every detail. And you do not need a folder full of documents for your experience to be worth recording. Tell us what happened, in your own words, and share only what you are comfortable providing.</p><div className="rb-actions"><Link className="rb-button red" href="/share-story" data-analytics-event="share_path_click" data-analytics-detail="homepage_contact">Share your MECCA experience</Link><a className="rb-button" href="mailto:insidemecca@mail2australia.com">Ask a question first</a></div></section>
</SitePage>}
