import Link from "next/link";
import type { Metadata } from "next";
import { PageHero, SitePage } from "../site-shell";

export const metadata: Metadata = { title:"MECCA Workplace Investigation Updates", description:"Follow new MECCA workplace culture analysis, document breakdowns, investigation progress, evidence gaps, corrections and research milestones." };

const phases=[
  ["01","Framework and safeguards","Complete","Research modules, evidence labels, consent pathways, corrections and right-of-reply standards are published."],
  ["02","Source collection","Current","First-hand accounts, supporting records and relevant public materials are being received, logged and assessed."],
  ["03","Pattern and systems analysis","Underway","Available material is being organised by research question, role, workplace type, period and evidence status."],
  ["04","Right of reply","Future stage","Proposed material criticisms will be put to MECCA and other relevant parties before findings are finalised."],
  ["05","Findings and recommendations","Future stage","Only supported conclusions will be published, with limitations, contradictions and responses represented."],
  ["06","Response and impact tracking","Future stage","Responses, accepted actions, timeframes and claimed progress will be recorded and assessed where evidence and access allow."],
];

const gaps=["Independent accounts across a wider range of roles, regions and employment periods","Records showing whether performance reviews, development plans and promotion processes operated consistently","Complaint timelines, correspondence and outcomes that can clarify what followed internal reporting","Leadership, HR and former executive perspectives on governance, monitoring and change after 2019","Evidence that challenges, qualifies or offers alternative explanations for recurring concerns"];

export default function Updates(){return <SitePage>
  <PageHero label="Project updates · Last reviewed 11 August 2026" title="Where the investigation is up to"><p>This page records what has been completed, what is still being worked on and what evidence is missing. A long task list is not the same thing as progress, and a submission count is not a finding.</p></PageHero>
  <section className="progress-summary"><div><span>Current phase</span><strong>Source collection and structured review</strong></div><div><span>Next milestone</span><strong>Module-level evidence assessment</strong></div><div><span>Findings status</span><strong>None published</strong></div></section>
  <section className="rb-section seo-entry"><p className="rb-kicker">Latest analysis · 11 August 2026</p><h2>Working at MECCA reviews: what employee experiences can and cannot establish</h2><p className="rb-lede">A source-led guide to reading review platforms, employee accounts, management commentary, company commitments and contradictory evidence without treating any one source as the whole workplace.</p><div className="rb-actions"><Link className="rb-button red" href="/analysis/working-at-mecca-reviews">Read the analysis</Link><Link className="rb-button" href="/analysis">View the analysis archive</Link></div></section>
  <section className="rb-section"><p className="rb-kicker">From source to follow-up</p><h2>How the work moves forward</h2><p className="rb-lede">The stages are shown in order, but they can overlap. New evidence may also send an earlier question back for more checking.</p><div className="progress-timeline">{phases.map(([n,t,s,d])=><article key={n}><span>{n}</span><div><small className={`progress-status ${s.toLowerCase().replaceAll(" ","-")}`}>{s}</small><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <section className="rb-section dark"><p className="rb-kicker">Right now</p><h2>What we are working on</h2><div className="rb-grid">{[["Accounts","Receiving first-hand accounts and recording what each contributor directly knows, along with their contact and use choices."],["Records","Reviewing relevant documents while keeping provenance, authenticity limits and confidentiality risks attached to the record."],["Comparison","Organising material by research question and looking for independent support, contradictions and alternative explanations."],["Public record","Keeping company statements, reporting, official records and open questions attributed to their sources."],["Documentary","Holding separate conversations about documentary participation. Agreeing to talk is not agreement to be recorded or published."],["Governance","Putting controls in place for conflicts, sensitive access, expert review and final editorial decisions."]].map(([t,d])=><article className="rb-card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="rb-section"><p className="rb-kicker">What is missing</p><h2>Evidence that would make the work stronger</h2><ul className="gap-list">{gaps.map(x=><li key={x}>{x}</li>)}</ul><p className="rb-note">A gap does not show that an event did or did not happen. It shows what we still need before reaching a responsible conclusion.</p></section>
  <section className="rb-section dark"><p className="rb-kicker">Next public milestone</p><h2>Show the evidence, question by question</h2><p className="rb-lede">The next milestone will set out what evidence exists for each research question, what remains disputed or unverified, and what further source work is needed. We will not promise a publication date before the evidence, consent, fairness and legal review are ready.</p><div className="rb-actions"><Link className="rb-button red" href="/share-story">Contribute to the research</Link><Link className="rb-button" href="/investigation">See the research questions</Link></div></section>
</SitePage>}
