import { SitePage } from "../../site-shell";
import { CaseStudy, type CaseStudyData } from "../case-study";

const study:CaseStudyData={
  reference:"001",
  title:"Reporting workplace concerns",
  subject:"Former employee account",
  evidenceStatus:"First-hand testimony with supporting material held privately",
  evidenceNote:"The contributor states that written responses, screenshots, messages and other material were provided during the workplace process. The material is not published here to protect privacy. The account remains attributed testimony and is not presented as an independently established finding.",
  categories:["Bullying and workplace culture","Speaking up","Bereavement","Psychological safety","Mental health","Workplace investigation","Workplace transfer","Management response"],
  sections:[
    {heading:"Overview",paragraphs:["This case records the experience of a former employee who reported workplace concerns after the death of an immediate family member.","The contributor states that concerns about workplace behaviour developed into a lengthy complaint process that affected their mental health, confidence in the organisation and decision to leave. Identifying information has been removed."]},
    {heading:"What happened",paragraphs:["Following the death of an immediate family member, the contributor alleges that comments and rumours relating to their bereavement were repeated back to them by another employee.","They say the comments left them isolated, distressed and increasingly uncomfortable returning to work. According to the contributor, the concerns were reported to management on multiple occasions and they repeatedly requested formal escalation, but felt dismissed rather than supported.","The contributor recalls being told they had “done bad things too” while trying to explain their concerns. They describe this conversation as a turning point in their confidence that the issue would be handled appropriately. As the situation continued, they say they no longer felt psychologically safe returning to that workplace."]},
    {heading:"Escalation",paragraphs:["The contributor states that the complaint did not progress to a formal workplace investigation until another person contacted head office on their behalf.","Once formally escalated, they attended multiple meetings and say they supplied written responses, screenshots, messages and other requested information. They describe the process as emotionally difficult because it required repeatedly revisiting distressing events while managing the effect on their mental health."]},
    {heading:"Support during the investigation",paragraphs:["The contributor acknowledges that the people involved in the formal investigation treated them respectfully. However, they say they felt unsupported overall.","They describe responsibility for progressing the complaint as resting largely with them and requiring repeated follow-up while they were experiencing significant distress. Although wellbeing resources were offered, the contributor says those services did not adequately address their circumstances or reduce the continuing impact of the process."]},
    {heading:"Resolution",paragraphs:["The contributor was ultimately transferred to another workplace, which enabled them to return to work in a different environment.","They say they were not informed of the following outcomes:"],items:["Whether the concerns had been substantiated","Whether workplace changes had been implemented","Whether any action had been taken following the investigation","How the matter had ultimately been resolved"]},
    {heading:"Overall outcome",paragraphs:["Although the transfer allowed the contributor to return to work, they state they did not regain confidence in the organisation or feel that the underlying concerns had been meaningfully resolved.","They believe the experience fundamentally changed how they viewed the workplace and their future within the company. The contributor ultimately chose to leave several months later."]},
    {heading:"Why this case matters",paragraphs:["This case raises questions about workplace systems rather than focusing on individual people. It may help guide further evidence collection, but it does not establish that the experience was widespread or systemic."],items:["How are workplace concerns managed when first reported?","What happens when an employee believes concerns are not being escalated?","How are employees supported while an investigation is ongoing?","What information should employees reasonably expect after an investigation concludes?","How can confidentiality be balanced with providing confidence that concerns were properly considered?"]},
  ],
  responseStatus:"No MECCA response to this anonymised case study is included at publication. If a substantive response is received, it will be attributed and added with the date received.",
  publicationNote:"Identifying details, exact workplace locations, dates and names are withheld. Supporting documents are held privately by the project and are not publicly released on this page.",
};

export default function CaseStudy001(){return <SitePage><CaseStudy study={study}/></SitePage>}
