import Link from "next/link";
import { PageHero, SitePage } from "../site-shell";

const modules = [
  {part:"A",id:"methodology",title:"How the work is done",objective:"This part sets the rules for collecting, checking and describing evidence. It also makes the limits of the research visible.",question:"How was the evidence collected, checked and analysed?",items:["Consent","Verification","Evidence grading","Limits","Privacy"]},
  {part:"B",id:"workplace-experiences",title:"What employees experienced",objective:"This is where we look at day-to-day working life and ask whether similar experiences appear across stores, regions, roles or periods of time.",question:"What did employees experience while working at MECCA?",items:["Culture","Bullying","Favouritism","Workload","Leadership","Mental health","Retaliation"]},
  {part:"C",id:"people-systems",title:"Performance and careers",objective:"MECCA has documented systems for performance, development and progression. This part asks how those systems worked in practice and whether people experienced them consistently.",question:"Did MECCA's people systems operate as described?",items:["Reviews","Career development","Development plans","Promotion","MECCAversity","Manager responsibilities","HR governance"]},
  {part:"D",id:"complaints",title:"Speaking up",objective:"Raising a concern is only the start of the story. We want to understand where reports went, what followed and how the employee was treated afterwards.",question:"What happened after employees raised concerns?",items:["HR","Stopline","Whistleblower systems","Investigations","Outcomes","Retaliation","Confidentiality"]},
  {part:"E",id:"documents",title:"Records",objective:"Records may support an account, contradict it or add context that memory alone cannot provide. This part keeps track of what each record can and cannot establish.",question:"What parts of an employee account can be checked against records?",items:["Employment","Performance","Promotion","Learning","Complaints","Exit records"]},
  {part:"F",id:"governance",title:"Leadership and accountability",objective:"This part looks beyond individual managers to the systems around them: who was responsible, what was monitored and what changed after problems were raised.",question:"How were workplace systems governed, monitored and improved?",items:["Store leaders","Regional leaders","HR","Head Office","Former executives"]},
  {part:"G",id:"documentary-interview",title:"Documentary interviews",objective:"The questionnaire records evidence. A documentary interview does something different: it explores what an experience meant to the person who lived it.",question:"What did these experiences mean to the people who lived them?",items:["Career","Relationships","Turning points","Impact","Reflection","What needs to change"]},
  {part:"H",id:"findings",title:"What the evidence supports",objective:"Possible conclusions are tested against all available evidence, including contradictions, alternative explanations and relevant company responses.",question:"What can the evidence responsibly support?",items:["Sources","Strength","Contradictions","Company response"]},
  {part:"I",id:"recommendations",title:"What should happen next",objective:"Recommendations come after findings. They must respond to problems the evidence actually establishes and identify who is in a position to act.",question:"What should change, and who can act?",items:["MECCA","Employees","Industry","Regulators"]},
];

export default function Investigation(){return <SitePage>
  <PageHero label="The investigation" title="What we are looking at, and why"><p>This project covers more than employee stories. It asks how MECCA&apos;s workplace systems were meant to work, what people experienced in practice, what the records show, and what can be responsibly concluded.</p><p>The work is divided into nine parts so testimony, documents, interviews, findings and recommendations do not get blurred together.</p><div className="rb-actions"><Link className="rb-button red" href="/share-story">Contribute to the research</Link><a className="rb-button" href="#modules">See the nine parts</a></div></PageHero>
  <nav className="if-index" aria-label="Investigation module index">{modules.map(m=><a key={m.part} href={`#${m.id}`}><span>{m.part}</span>{m.title}</a>)}</nav>
  <section id="modules" className="if-modules" aria-label="Research modules">{modules.map(m=><article id={m.id} className="if-module" key={m.part}><header><span>Part {m.part}</span></header><div className="if-module-body"><div><h2>{m.title}</h2><p className="if-objective">{m.objective}</p><div className="if-question"><strong>The question</strong><blockquote>{m.question}</blockquote></div></div><aside><strong>Included in this part</strong><ul>{m.items.map(x=><li key={x}>{x}</li>)}</ul>{m.part==="B"&&<Link href="/share-story/research-questionnaire">Complete the research questionnaire</Link>}{m.part==="E"&&<Link href="/share-story/evidence">Provide relevant records</Link>}{m.part==="G"&&<Link href="/documentary">Ask about a documentary interview</Link>}</aside></div></article>)}</section>
</SitePage>}
