import Link from "next/link";
import { PageHero, SitePage } from "../../site-shell";

const headcount = [
  ["End of 2023", "More than 8,000 people", "2023 Modern Slavery Statement", "Regulatory filing / company statement", "Different entities and workforce definitions may be included"],
  ["Current page reviewed Aug 2026", "More than 7,500 team members", "MECCA WGEA gender pay data page", "Company statement", "Page is undated and does not define the count"],
  ["Q1 2026", "5,589 profiles", "Revelio Labs, as reproduced in Part F", "Commercial estimate", "Public-profile model, not payroll headcount"],
  ["Current page reviewed Aug 2026", "5,000+", "MECCA LinkedIn profile, as recorded in Part F", "Platform profile", "Range and update date are unclear"],
];
const workforce = [
  ["Median tenure", "2.5 years", "Revelio Labs", "Commercial estimate based on professional-profile data"],
  ["Estimated workforce change", "Down 10.5% from Q2 2023 to Q1 2026", "Part F calculation from Revelio Labs series", "A change in tracked profiles is not a verified employee-turnover rate"],
  ["Long-tenure distribution", "SignalHire suggests a high share at five years or more", "SignalHire", "Methodology unclear and inconsistent with the Revelio median"],
];
const finances = [
  ["2022", "MECCA Brands Pty Ltd", "$971m", "$26.9m", "Media-reported figure reproduced in Part F"],
  ["2023", "MECCA Brands Pty Ltd", "$1.21bn", "$27.8m", "Media-reported figure reproduced in Part F"],
  ["2024", "MECCA Brands Pty Ltd", "$1.28bn", "$22.7m", "Media-reported figure reproduced in Part F"],
  ["2024", "RTCH Pty Ltd", "$1.36bn", "$111.1m", "Parent-entity figure reproduced in Part F"],
  ["2025", "RTCH Pty Ltd", "$1.43bn", "$111.1m / US$125.9m reported", "Conflicting reports may reflect currency, period or reporting basis; direct accounts required"],
];
const claimChanges = [
  ["Internal promotion", "A 2017 public presentation reportedly said 90% of promotions were filled internally.", "Current wording refers generally to strengthening pathways to promote from within.", "Historical statement needs an archived primary recording and current policy data before comparison."],
  ["Training investment", "Publicly reported figures moved from about 3% of turnover to 4%, then back to approximately 3%.", "The figures come from different years and source types.", "A wording change does not establish a reduction in actual spending."],
  ["Training hours", "A 200-hour first-year training figure appeared in interviews and presentations.", "Part F did not locate the figure on the current MECCA website.", "Absence from a current webpage is not evidence the program ended."],
  ["Best Places to Work", "MECCA was publicly described as appearing for five consecutive years through 2018.", "Part F found no later listing.", "Participation is opt-in. No later listing does not establish a decline in workplace quality."],
];

export default function WorkforceFinancialData(){return <SitePage>
  <PageHero label="Research Centre / Workforce and financial data" title="What the numbers tell us, and where they stop"><p>This page compares MECCA Brands Pty Ltd workforce claims, third-party estimates and reported financial figures source by source. It tests what the available material can support without turning an estimate or a gap into a finding.</p><div className="rb-actions"><a className="rb-button red" href="#retention-claim">Look at the retention claim</a><a className="rb-button" href="#source-notes">Read the source notes</a></div></PageHero>
  <section className="rc-status-strip"><div><span>Research status</span><strong>Part F reviewed, primary-source checks ongoing</strong></div><div><span>Core limitation</span><strong>No verified turnover or retention rate located</strong></div><div><span>Last reviewed</span><strong>4 August 2026</strong></div></section>
  <section className="rb-section" id="retention-claim"><p className="rb-kicker">A company claim under examination</p><h2>&ldquo;Extraordinary tenure and loyalty&rdquo;</h2><p className="rb-lede">MECCA&apos;s WGEA gender pay data page attributes this description to its Chief People Officer. The page also states that the business has more than 7,500 team members, but it does not publish a turnover rate, retention rate, median tenure, calculation method or benchmark supporting the description.</p><div className="rc-verdict"><span className="rc-label company-statement">Company statement</span><div><strong>What we can verify</strong><p>The description appears in a published company statement. The underlying workforce claim is not independently verified by the material reviewed.</p></div></div><p className="rb-note">This does not mean the statement is false. It means the published evidence is not enough to test the word &ldquo;extraordinary&rdquo; responsibly.</p></section>
  <section className="rb-section dark"><p className="rb-kicker">02 / Headcount comparison</p><h2>Different sources count different things.</h2><p className="rb-lede">The figures below should not be placed on one continuous chart as though they use the same population or method.</p><div className="rc-data-table" role="table" aria-label="Headcount source comparison"><div className="rc-data-head" role="row"><span>Date</span><span>Figure</span><span>Source</span><span>Class</span><span>Known limitation</span></div>{headcount.map(row=><div role="row" key={row[0]+row[2]}>{row.map((cell,i)=><span role="cell" key={i}>{cell}</span>)}</div>)}</div></section>
  <section className="rb-section"><p className="rb-kicker">03 / Third-party workforce intelligence</p><h2>Useful indicators, not payroll records.</h2><div className="rb-grid">{workforce.map(([title,value,source,caveat])=><article className="rb-card" key={title}><span className="rc-label media-report">Third-party estimate</span><h3>{title}</h3><p className="rc-big-number">{value}</p><p><strong>Source:</strong> {source}</p><p>{caveat}</p></article>)}</div><p className="rb-note">Revelio Labs and SignalHire appear to model workforce information from public professional profiles. Casual, seasonal, low-profile and departed workers may be captured differently. The two services also produce tenure pictures that do not readily reconcile.</p></section>
  <section className="rb-section dark"><p className="rb-kicker">04 / Reported financial snapshot</p><h2>Entity boundaries matter.</h2><p className="rb-lede">Part F compiles the following reported figures. MECCA Brands Pty Ltd is the retail entity identified in the report; RTCH Pty Ltd is identified as a parent entity. Their revenue and profit figures are not interchangeable.</p><div className="rc-data-table" role="table" aria-label="Reported financial figures"><div className="rc-data-head" role="row"><span>Year</span><span>Entity</span><span>Revenue</span><span>Net profit</span><span>Status</span></div>{finances.map(row=><div role="row" key={row[0]+row[1]}>{row.map((cell,i)=><span role="cell" key={i}>{cell}</span>)}</div>)}</div><p className="rc-caution"><strong>No inference about intercompany transactions</strong>The difference between entity-level results does not, by itself, establish licensing fees, management charges, profit shifting or any other cause. Consolidated accounts and related-party notes are required.</p></section>
  <section className="rb-section"><p className="rb-kicker">05 / Public claims over time</p><h2>Changed wording is a research lead, not proof of why it changed.</h2><div className="rc-change-list">{claimChanges.map(([topic,earlier,current,limit],i)=><article key={topic}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{topic}</h3><p><strong>Earlier record:</strong> {earlier}</p><p><strong>Current comparison:</strong> {current}</p><small>{limit}</small></div></article>)}</div><p className="rb-note">Possible explanations such as website migration, pandemic disruption, correction or a communications shift remain hypotheses unless MECCA provides an explanation or contemporaneous records establish one.</p></section>
  <section className="rb-section dark"><p className="rb-kicker">06 / Official records</p><h2>What selected primary sources establish.</h2><div className="rb-grid"><article className="rb-card"><span className="rc-label verified-primary-fact">Verified primary fact</span><h3>2023 Modern Slavery Statement</h3><p>The official register identifies MECCA Brands Pty Ltd and MECCA Brands NZ Pty Ltd as reporting entities and records annual revenue of $1 billion or more. The statement reports more than 8,000 people at the end of 2023.</p><a href="https://modernslaveryregister.gov.au/statements/18286/" target="_blank" rel="noreferrer">Official register entry</a></article><article className="rb-card"><span className="rc-label verified-primary-fact">Verified primary fact</span><h3>ASIC infringement notices</h3><p>ASIC states that three MECCA-associated companies paid a combined $594,000 after alleged late lodgement of FY24 audited financial reports. ASIC expressly states that payment is not an admission of guilt or liability.</p><a href="https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2026-releases/26-057mr-mecca-companies-pay-594-000-in-infringement-notices-for-failing-to-lodge-financial-reports-on-time/" target="_blank" rel="noreferrer">ASIC media release 26-057MR</a></article><article className="rb-card"><span className="rc-label company-statement">Company statement</span><h3>WGEA gender pay data page</h3><p>The current page states more than 7,500 team members, 95% women, more than 75% of senior leadership roles held by women, and the tenure-and-loyalty description examined above.</p><a href="https://www.mecca.com/en-nz/m-pact/people/gender-pay-data/" target="_blank" rel="noreferrer">MECCA WGEA gender pay data page</a></article></div></section>
  <section className="rb-section"><p className="rb-kicker">07 / Gender pay data</p><h2>Different measures answer different questions.</h2><p className="rb-lede">The supplied recent-developments dossier records MECCA&apos;s published average total-remuneration gender pay gap as 30% in favour of men. It also records MECCA&apos;s statements that there is no pay gap across store teams and that the senior-leadership measure is -6.8%, favouring women, with women holding 77% of C-suite and General Manager roles.</p><div className="rc-verdict"><span className="rc-label company-statement">Company statement</span><div><strong>Interpretation limit</strong><p>These figures use different populations and measures. They should not be combined into a single conclusion about equal pay, representation or progression without the underlying WGEA employer dataset and role-level methodology.</p></div></div><p className="rb-note">The dossier also records independent commentary about MECCA&apos;s ranking among large employers. That ranking has not been promoted here because an independent check against the relevant WGEA comparison set has not been completed.</p></section>
  <section className="rb-section"><p className="rb-kicker">08 / Evidence gaps</p><h2>What would materially improve the analysis.</h2><div className="rc-gap-grid">{[["Payroll-defined headcount","Year-end and average headcount using a consistent definition across retail, support, distribution, casual and New Zealand workforces."],["Turnover and retention","Voluntary and involuntary turnover, retention and regrettable-loss rates with a stated period and benchmark."],["Tenure distribution","Payroll-derived median and average tenure by workforce group, not public-profile estimates."],["Audited financial statements","Entity and consolidated accounts, related-party notes and employee-benefit disclosures."],["WGEA employer data","Direct employer-level extracts and retail-industry comparisons from WGEA."],["Historical source preservation","Dated captures or recordings for promotion, training and employer-brand claims."]].map(([t,d])=><article key={t}><span className="rc-label evidence-gap">Evidence gap</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="rb-section dark" id="source-notes"><p className="rb-kicker">Source and legal notes</p><h2>How to read this section.</h2><p className="rb-lede">This page is based on <em>Part F - Turnover, Tenure &amp; Financial Deep Dive</em>, dated 4 August 2026, checked against selected official sources. Part F is a research synthesis, not an audited financial report or legal finding. Commercial estimates and media-reported figures remain attributed. No workforce estimate establishes why headcount changed, whether turnover was voluntary, or whether staffing was adequate.</p><p className="rb-note">Financial information is historical research context, not investment, accounting or legal advice. MECCA Brands Pty Ltd and RTCH Pty Ltd must remain separately identified. Allegations, regulatory notices and payment of infringement notices must not be described as convictions or admissions where the official source says otherwise.</p><div className="rb-actions"><Link className="rb-button red" href="/methodology">Evidence methodology</Link><Link className="rb-button" href="/research-centre/investigation-notebook">Investigation notebook</Link></div></section>
  </SitePage>}
